Create iproute.IPRoute() inside a context
IPRoute() object must be closed once is no longer used. This is done
automatically calling it inside its own context. If IPRoute() object
is not closed, the following error is raised after many calls:
  OSError: [Errno 24] Too many open files

Change-Id: I37ee291c22c2c3933ee229bfc939a4481898626c
Closes-Bug: #1807949