Fix mypy errors
Note that the misc error is disabled because the failure is caused by
the typing definitions in testscenarios.

error: Definition of "run" in base class "WithScenarios" is
incompatible with definition in base class "TestCase"  [misc]

Change-Id: Iea51c602d17726e394b07d338ef752153fbad8df
Signed-off-by: Takashi Kajinami <kajinamit@oss.nttdata.com>